[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "bun-console"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
crossterm = "0.24.0"
napi = "2.11"
napi-derive = "2.11"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
