/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function termSetRawMode(mode: number): number
export function termGetRawMode(): number
export function termGetColumns(): number
export function termGetRows(): number
