[package]
name = "bun-console-ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.24.0"
nanoserde = "0.1.30"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
