(module
  (type (;0;) (func))
  (type (;1;) (func (param externref) (result i32)))
  (type (;2;) (func (param i32 i32 i32 i32) (result i32)))

  (import "wasi_snapshot_preview1" "fd_write" 
    (func $fd_write (param externref i32 i32 i32 i32) (result i32)))
  (global (;0;) (mut externref) (ref.null extern))

  (func (export "_start") (type 1) (param externref) (result i32)
    (local.get 0) (;get externref param0;)
    (global.set 0) (;set externref as global0;)
    (call $print (i32.const 32) (i32.const 13))
    (call $print (i32.const 64) (i32.const 11))
    (i32.const 0)
  )
  (func $print (param $ptr i32) (param $len i32)
    (i32.store (i32.const 8) (local.get $len))
    (i32.store (i32.const 4) (local.get $ptr))
        (drop (call $fd_write
          (global.get 0)
          (i32.const 1)
          (i32.const 4)
          (i32.const 1)
          (i32.const 0)))
  )
  (memory (export "memory") 1)
  (data (i32.const 32) "Hello _start\0a")
  (data (i32.const 64) "Hello done\0a")
)