name: Publish bun-fs-js Package

on:
  workflow_dispatch:
  push:
    branches:
      - gh_actions

concurrency:
  group: bunfsjs-publish
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Try npmrc setup
        run: echo -e "@netapplabs:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@netapplabs'

      - name: Debug config files
        run: cat ./bunfig.toml && cat ~/.npmrc

      - name: Install dependencies
        run: bun install
        working-directory: packages/bun-fs-js
        env:
          BUN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Bump version
        run: bunx standard-version
        working-directory: packages/bun-fs-js

      - name: Build package
        run: bun run build
        working-directory: packages/bun-fs-js

      - name: Publish package
        run: bun publish
        working-directory: packages/bun-fs-js
        env:
          BUN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push version bump
        run: |
          git push
