# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: wasmin-ci

on:
  push:
    branches: [ "improved_packaging" ]
  pull_request:
    branches: [ "improved_packaging" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [ 20.x ]
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn
      run: npm install --global yarn
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        check-latest: true
    - name: bun
      uses: oven-sh/setup-bun@v1
    - name: deno
      uses: denoland/setup-deno@v1
    - name: install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test