# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: wasmin-ci

on:
 push:
   branches: [ "*" ]
   tags:
      - '[0-9]+.[0-9]+.[0-9]+'
 pull_request:
   branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write
      packages: write

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        include:
          - os: ubuntu-latest
            wasmin_bun_artifact: wasmin-bun
            wasmin_bun_asset: wasmin-bun-linux-amd64
            wasmin_deno_artifact: wasmin-deno
            wasmin_deno_asset: wasmin-deno-linux-amd64
            wasmin_node_artifact: wasmin-node
            wasmin_node_asset: wasmin-node-linux-amd64
            node-version: 22.x
          - os: macos-latest
            wasmin_bun_artifact: wasmin-bun
            wasmin_bun_asset: wasmin-bun-macos-arm64
            wasmin_deno_artifact: wasmin-deno
            wasmin_deno_asset: wasmin-deno-macos-arm64
            wasmin_node_artifact: wasmin-node
            wasmin_node_asset: wasmin-node-macos-arm64
            node-version: 22.x
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn
      run: npm install --global yarn
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        check-latest: true
    - name: bun
      uses: oven-sh/setup-bun@v2
    - name: deno
      uses: denoland/setup-deno@v2
    - name: Set up GH Package Registry Auth
      run: echo "@netapplabs:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
    - name: yarn-install
      run: yarn install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
    - name: build-exe-bun
      run: ./build-exe-bun.sh
    - name: build-exe-deno
      run: ./build-exe-deno.sh
    - name: build-exe-node
      run: ./build-exe-node.sh
    # Upload binary
    - name: Upload wasmin-bun binary to release on main
      if: ${{github.ref == 'main'}}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./${{ matrix.wasmin_bun_artifact }}
        asset_name: ${{ matrix.wasmin_bun_asset }}
        tag: latest
        overwrite: true
    - name: Upload wasmin-bun binary to release not on main
      if: ${{github.ref != 'main'}}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./${{ matrix.wasmin_bun_artifact }}
        asset_name: ${{ matrix.wasmin_bun_asset }}
        tag: ${{ github.ref }}
        overwrite: true
    - name: Upload wasmin-deno binary to release on main
      if: ${{github.ref == 'main'}}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./${{ matrix.wasmin_deno_artifact }}
        asset_name: ${{ matrix.wasmin_deno_asset }}
        tag: latest
        overwrite: true
    - name: Upload wasmin-deno binary to release not on main
      if: ${{github.ref == 'main'}}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./${{ matrix.wasmin_deno_artifact }}
        asset_name: ${{ matrix.wasmin_deno_asset }}
        tag: ${{ github.ref }}
        overwrite: true
    - name: Upload wasmin-node binary to release on main
      if: ${{github.ref == 'main'}}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./${{ matrix.wasmin_node_artifact }}
        asset_name: ${{ matrix.wasmin_node_asset }}
        tag: latest
        overwrite: true
    - name: Upload wasmin-node binary to release not on main
      if: ${{github.ref != 'main'}}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./${{ matrix.wasmin_node_artifact }}
        asset_name: ${{ matrix.wasmin_node_asset }}
        tag: ${{ github.ref }}
        overwrite: true
    - name: Setup Docker Buildx
      if: ${{matrix.os == 'ubuntu-latest'}}
      uses: docker/setup-buildx-action@v2
    - name: Log in to the Container registry
      if: ${{matrix.os == 'ubuntu-latest'}}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      if: ${{matrix.os == 'ubuntu-latest'}}
      id: meta
      uses: docker/metadata-action@v5
      with:
        images:
          ghcr.io/${{ github.repository }}
    - name: Build and push Docker images
      if: ${{matrix.os == 'ubuntu-latest'}}
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}