name: Publish tsconfig Package

on:
  workflow_dispatch:
  push:
    branches:
      - gh_actions

concurrency:
  group: tsconfig-publish
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'

      - name: Set up GH Package Registry Auth
        run: |
          echo "@netapplabs:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: npm install --prefix .
        working-directory: packages/tsconfig

      - name: Build package
        run: npm run build --prefix .
        working-directory: packages/tsconfig

      - name: Publish package
        run: npm publish --prefix .
        working-directory: packages/tsconfig
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}